# This file is automatically generated. Do not edit.

PXEngine.licenseKey('G6OEU-68BUE-C8NKI-E3GHO-SV7NO-C2QN0-RSKET-6B9C5-707JS-451BA-IE4OP-HG0C6-SHC0S-P68JG-I3LF7-J6', forUser:'jason@waldrip.net')

def style(str)
  PXEngine.styleSheetFromSource(str, withOrigin:0)
  PXEngine.applyStylesheets
end
