# This file is automatically generated. Do not edit.

PXEngine.licenseKey('J144G-PVVDP-LRTHO-P7JQQ-TTJJC-34J9F-RPF3C-IS0GG-L0JE0-HDBFQ-4DBNN-M5KOI-E5S40-RFOIR-VG51L-2O', forUser:'jason@waldrip.net')

def style(str)
  PXEngine.styleSheetFromSource(str, withOrigin:0)
  PXEngine.applyStylesheets
end
